### ISSUE TITLE
SQL Port in Config

### ISSUE THREAD

**Issue by dwu300** [BPMspaceUG/APMS2#43]
- SQL Port ins Config file speichern und in APMS einlesen

est = 1h

**Comment by Kuhlig** [comment]
1 h ok 

 

Von: wu <notifications@github.com> 
Gesendet: Freitag, 28. Februar 2020 09:20
An: BPMspaceUG/APMS2 <APMS2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [BPMspaceUG/APMS2] SQL Port in Config (#43)

 

*	SQL Port ins Config file speichern und in APMS einlesen

est = 1h

**Comment by dwu300** [comment]
Add mini file to save recent projects ~1-2h

**Comment by Kuhlig** [comment]
1h – nie im Leben 2 h – sonst NICHT machen 

 

Von: wu <notifications@github.com> 
Gesendet: Montag, 2. März 2020 13:36
An: BPMspaceUG/APMS2 <APMS2@noreply.github.com>
Cc: Robert Kuhlig <rob@bpmspace.com>; Comment <comment@noreply.github.com>
Betreff: Re: [BPMspaceUG/APMS2] SQL Port in Config (#43)

 

Add mini file to save recent projects ~1-2h
