### ISSUE TITLE
The IDs should be hidden by default, but viewed by hover

### ISSUE THREAD

**Issue by dwu300** [BPMspaceUG/APMS2#8]
The Primary-IDs of all Tables should be hidden by default but if the Mouse is moved over it, it should be visible by hover.

**Comment by dwu300** [comment]
et = 1h

**Comment by Kuhlig** [comment]
ok

 

Von: wu <notifications@github.com> 
Gesendet: Dienstag, 25. Februar 2020 09:48
An: BPMspaceUG/APMS2 <APMS2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [BPMspaceUG/APMS2] The IDs should be hidden by default, but viewed by hover (#8)

 

et = 1h
